//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeDataEntities : DbContext
    {
        public EmployeeDataEntities()
            : base("name=EmployeeDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    
        public virtual int USP_Employee_D00(Nullable<int> i_INT_EmployeeID, string i_CHR_EmployeeNumber, string i_CHR_Name, string i_CHR_DepartmentNumber, string i_CHR_JobTitle, Nullable<System.DateTime> i_DTE_HireDate)
        {
            var i_INT_EmployeeIDParameter = i_INT_EmployeeID.HasValue ?
                new ObjectParameter("I_INT_EmployeeID", i_INT_EmployeeID) :
                new ObjectParameter("I_INT_EmployeeID", typeof(int));
    
            var i_CHR_EmployeeNumberParameter = i_CHR_EmployeeNumber != null ?
                new ObjectParameter("I_CHR_EmployeeNumber", i_CHR_EmployeeNumber) :
                new ObjectParameter("I_CHR_EmployeeNumber", typeof(string));
    
            var i_CHR_NameParameter = i_CHR_Name != null ?
                new ObjectParameter("I_CHR_Name", i_CHR_Name) :
                new ObjectParameter("I_CHR_Name", typeof(string));
    
            var i_CHR_DepartmentNumberParameter = i_CHR_DepartmentNumber != null ?
                new ObjectParameter("I_CHR_DepartmentNumber", i_CHR_DepartmentNumber) :
                new ObjectParameter("I_CHR_DepartmentNumber", typeof(string));
    
            var i_CHR_JobTitleParameter = i_CHR_JobTitle != null ?
                new ObjectParameter("I_CHR_JobTitle", i_CHR_JobTitle) :
                new ObjectParameter("I_CHR_JobTitle", typeof(string));
    
            var i_DTE_HireDateParameter = i_DTE_HireDate.HasValue ?
                new ObjectParameter("I_DTE_HireDate", i_DTE_HireDate) :
                new ObjectParameter("I_DTE_HireDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Employee_D00", i_INT_EmployeeIDParameter, i_CHR_EmployeeNumberParameter, i_CHR_NameParameter, i_CHR_DepartmentNumberParameter, i_CHR_JobTitleParameter, i_DTE_HireDateParameter);
        }
    
        public virtual int USP_Employee_I00(string i_CHR_EmployeeNumber, string i_CHR_Name, string i_CHR_DepartmentNumber, string i_CHR_JobTitle, Nullable<System.DateTime> i_DTE_HireDate)
        {
            var i_CHR_EmployeeNumberParameter = i_CHR_EmployeeNumber != null ?
                new ObjectParameter("I_CHR_EmployeeNumber", i_CHR_EmployeeNumber) :
                new ObjectParameter("I_CHR_EmployeeNumber", typeof(string));
    
            var i_CHR_NameParameter = i_CHR_Name != null ?
                new ObjectParameter("I_CHR_Name", i_CHR_Name) :
                new ObjectParameter("I_CHR_Name", typeof(string));
    
            var i_CHR_DepartmentNumberParameter = i_CHR_DepartmentNumber != null ?
                new ObjectParameter("I_CHR_DepartmentNumber", i_CHR_DepartmentNumber) :
                new ObjectParameter("I_CHR_DepartmentNumber", typeof(string));
    
            var i_CHR_JobTitleParameter = i_CHR_JobTitle != null ?
                new ObjectParameter("I_CHR_JobTitle", i_CHR_JobTitle) :
                new ObjectParameter("I_CHR_JobTitle", typeof(string));
    
            var i_DTE_HireDateParameter = i_DTE_HireDate.HasValue ?
                new ObjectParameter("I_DTE_HireDate", i_DTE_HireDate) :
                new ObjectParameter("I_DTE_HireDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Employee_I00", i_CHR_EmployeeNumberParameter, i_CHR_NameParameter, i_CHR_DepartmentNumberParameter, i_CHR_JobTitleParameter, i_DTE_HireDateParameter);
        }
    
        public virtual ObjectResult<USP_Employee_S00_Result> USP_Employee_S00()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Employee_S00_Result>("USP_Employee_S00");
        }
    
        public virtual int USP_Employee_U00(Nullable<int> i_INT_EmployeeID, string i_CHR_EmployeeNumber, string i_CHR_Name, string i_CHR_DepartmentNumber, string i_CHR_JobTitle, Nullable<System.DateTime> i_DTE_HireDate)
        {
            var i_INT_EmployeeIDParameter = i_INT_EmployeeID.HasValue ?
                new ObjectParameter("I_INT_EmployeeID", i_INT_EmployeeID) :
                new ObjectParameter("I_INT_EmployeeID", typeof(int));
    
            var i_CHR_EmployeeNumberParameter = i_CHR_EmployeeNumber != null ?
                new ObjectParameter("I_CHR_EmployeeNumber", i_CHR_EmployeeNumber) :
                new ObjectParameter("I_CHR_EmployeeNumber", typeof(string));
    
            var i_CHR_NameParameter = i_CHR_Name != null ?
                new ObjectParameter("I_CHR_Name", i_CHR_Name) :
                new ObjectParameter("I_CHR_Name", typeof(string));
    
            var i_CHR_DepartmentNumberParameter = i_CHR_DepartmentNumber != null ?
                new ObjectParameter("I_CHR_DepartmentNumber", i_CHR_DepartmentNumber) :
                new ObjectParameter("I_CHR_DepartmentNumber", typeof(string));
    
            var i_CHR_JobTitleParameter = i_CHR_JobTitle != null ?
                new ObjectParameter("I_CHR_JobTitle", i_CHR_JobTitle) :
                new ObjectParameter("I_CHR_JobTitle", typeof(string));
    
            var i_DTE_HireDateParameter = i_DTE_HireDate.HasValue ?
                new ObjectParameter("I_DTE_HireDate", i_DTE_HireDate) :
                new ObjectParameter("I_DTE_HireDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Employee_U00", i_INT_EmployeeIDParameter, i_CHR_EmployeeNumberParameter, i_CHR_NameParameter, i_CHR_DepartmentNumberParameter, i_CHR_JobTitleParameter, i_DTE_HireDateParameter);
        }
    }
}
